// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package operations

import (
	"github.com/inkeep/ai-api-go/models/components"
	"github.com/inkeep/ai-api-go/types/stream"
	"net/http"
)

type CreateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	ChatResult *components.ChatResult
	// Successful Response
	ChatResultStream *stream.EventStream[components.ChatResultStream]
}

func (o *CreateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateResponse) GetChatResult() *components.ChatResult {
	if o == nil {
		return nil
	}
	return o.ChatResult
}

func (o *CreateResponse) GetChatResultStream() *stream.EventStream[components.ChatResultStream] {
	if o == nil {
		return nil
	}
	return o.ChatResultStream
}
