// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/inkeep/ai-api-go/models/components"
)

// HTTPValidationError - Validation Error
type HTTPValidationError struct {
	Detail []components.ValidationError `json:"detail,omitempty"`
}

var _ error = &HTTPValidationError{}

func (e *HTTPValidationError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
