// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package components

type ChatResult struct {
	ChatSessionID string           `json:"chat_session_id"`
	Message       AssistantMessage `json:"message"`
}

func (o *ChatResult) GetChatSessionID() string {
	if o == nil {
		return ""
	}
	return o.ChatSessionID
}

func (o *ChatResult) GetMessage() AssistantMessage {
	if o == nil {
		return AssistantMessage{}
	}
	return o.Message
}
