// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package components

import (
	"github.com/inkeep/ai-api-go/internal/utils"
)

// ChatResultMessageChunkEvent - A server-sent event containing a chunk of the message.
type ChatResultMessageChunkEvent struct {
	event string       `const:"message_chunk" json:"event"`
	Data  MessageChunk `json:"data"`
}

func (c ChatResultMessageChunkEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatResultMessageChunkEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ChatResultMessageChunkEvent) GetEvent() string {
	return "message_chunk"
}

func (o *ChatResultMessageChunkEvent) GetData() MessageChunk {
	if o == nil {
		return MessageChunk{}
	}
	return o.Data
}
