// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Citation struct {
	Number *int64  `json:"number,omitempty"`
	Record Record  `json:"record"`
	HitURL *string `json:"hit_url,omitempty"`
}

func (o *Citation) GetNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.Number
}

func (o *Citation) GetRecord() Record {
	if o == nil {
		return Record{}
	}
	return o.Record
}

func (o *Citation) GetHitURL() *string {
	if o == nil {
		return nil
	}
	return o.HitURL
}
