// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RecordsCited struct {
	Citations []Citation `json:"citations"`
}

func (o *RecordsCited) GetCitations() []Citation {
	if o == nil {
		return []Citation{}
	}
	return o.Citations
}
