// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Role string

const (
	RoleUser Role = "user"
)

func (e Role) ToPointer() *Role {
	return &e
}

func (e *Role) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user":
		*e = Role(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Role: %v", v)
	}
}

type UserMessage struct {
	Role    Role   `json:"role"`
	Content string `json:"content"`
}

func (o *UserMessage) GetRole() Role {
	if o == nil {
		return Role("")
	}
	return o.Role
}

func (o *UserMessage) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}
