// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package components

import (
	"github.com/inkeep/ai-api-go/internal/utils"
)

type UserMessage struct {
	role    string `const:"user" json:"role"`
	Content string `json:"content"`
}

func (u UserMessage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserMessage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UserMessage) GetRole() string {
	return "user"
}

func (o *UserMessage) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}
