workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://raw.githubusercontent.com/inkeep/chat-api-openapi-schema/main/openapi.yaml
targets:
    ai-api:
        target: go
        source: my-source
